import type { NextPage } from "next";
import Head from "next/head";
import { io } from "socket.io-client";

const socket = io("http://localhost:1337");

const Home: NextPage = () => {
  // socket.emit("room:create", { userId: "siema" });
  socket.emit("online");
  return (
    <Head>
      <title>Tic Tac Toe</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Home;
